#!/usr/bin/env bash
# installs nginx on a remote server and configures it
sudo apt-get update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
