#!/usr/bin/env bash
# installs nginx on a remote server and configures it
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/^.*listen.*$/listen 80;/g' /etc/nginx/sites-available/default
sudo kill -s HUP $(cat /var/run/nginx.pid)
curl_output=$(curl -s 127.0.0.1)
if [[ $curl_output == *"Hello World!"* ]]; then
	echo "Nginx successfully installed and serving 'Hello World!'"
else
	echo "Something went wrong with Nginx installation or configuration"
fi
