#!/usr/bin/env bash
# installs nginx on a remote server and configures it
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/^.*listen.*$/listen 80;/g' /etc/nginx/sites-available/default
sudo service nginx restart || sudo /etc/init.d/nginx restart
echo "<html><body><h1>Hello World!</h1></body></html>" | sudo tee /var/www/html/index.html > /dev/null
